### ISSUE TITLE
Failed compile on aarch64 (0.17.0)

### ISSUE THREAD

**Issue by loganmc10** [PolyMeilex/rfd#293]
I'm not sure why this only happens on aarch64, this error doesn't happen with my x86_64 build

```
error[E0308]: mismatched types
Error:    --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rfd-0.17.0/src/backend/xdg_desktop_portal/portal/libdbus.rs:304:37
    |
304 |                 Some(CStr::from_ptr(out).to_owned())
    |                      -------------- ^^^ expected `*const u8`, found `*const i8`
    |                      |
    |                      arguments to this function are incorrect
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`
note: associated function defined here
   --> /rustc/ded5c06cf21d2b93bffd5d884aa6e96934ee4234/library/core/src/ffi/c_str.rs:253:25
```

See here: https://github.com/gopher64/gopher64/actions/runs/20710074348/job/59450741904

**Comment by loganmc10** [comment]
It seems that the problem is that the type passed to `from_ptr` is actually a "c_char", which is unsigned on aarch64, but signed for x86_64
